// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMk_FthS_HnsiWRUPKee3k3b_ALzZBono',
    appId: '1:628287062529:web:5f7e664a01130a83637600',
    messagingSenderId: '628287062529',
    projectId: 'inclass14v1',
    authDomain: 'inclass14v1.firebaseapp.com',
    storageBucket: 'inclass14v1.firebasestorage.app',
    measurementId: 'G-4V03F7WDE8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ4NpRio5Yh6FxdJ4bJLeUruaPKMoIgUA',
    appId: '1:628287062529:android:1643c4796bb8234f637600',
    messagingSenderId: '628287062529',
    projectId: 'inclass14v1',
    storageBucket: 'inclass14v1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDU5SirXKghYK0joDTw0RwaQfRlntEyMTY',
    appId: '1:628287062529:ios:564c370a040cbec6637600',
    messagingSenderId: '628287062529',
    projectId: 'inclass14v1',
    storageBucket: 'inclass14v1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDU5SirXKghYK0joDTw0RwaQfRlntEyMTY',
    appId: '1:628287062529:ios:564c370a040cbec6637600',
    messagingSenderId: '628287062529',
    projectId: 'inclass14v1',
    storageBucket: 'inclass14v1.firebasestorage.app',
    iosBundleId: 'com.example.firebaseSetup',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMk_FthS_HnsiWRUPKee3k3b_ALzZBono',
    appId: '1:628287062529:web:6b3f536a3eed5402637600',
    messagingSenderId: '628287062529',
    projectId: 'inclass14v1',
    authDomain: 'inclass14v1.firebaseapp.com',
    storageBucket: 'inclass14v1.firebasestorage.app',
    measurementId: 'G-2S8ZRRDNTP',
  );
}
